language: elixir
elixir:
- 1.7.4
otp_release:
- '20.0'

cache:
  directories:
    - deps

env:
  global:
  - LOCAL_POSTGRES_USERNAME=postgres LOCAL_POSTGRES_PASSWORD=postgres
services: "-postgesql"
addons:
  postgresql: '9.6'
sudo: false

stages:
  - test
  - name: push
    if: branch = master
  - name: release
    if: branch = master
jobs:
  include:
    - stage: test
      script: ./build_scripts/test
    - stage: push
      name: "Register Container Image"
      script: ./build_scripts/push_container
    - stage: release
      script: ./build_scripts/release_container
