language: elixir
elixir:
- 1.7.4
otp_release:
- '20.0'

cache:
  directories:
    - deps

env:
  global:
  - LOCAL_POSTGRES_USERNAME=postgres LOCAL_POSTGRES_PASSWORD=postgres
services: "-postgesql"
addons:
  postgresql: '9.6'
sudo: false

jobs:
  include:
    - stage: test
      script: ./build_scripts/test
    - stage: setup
      name: "Ensure setup"
      script: ./build_scripts/ensure_setup
    - stage: push
      name: "Register Container Image"
      script: ./build_scripts/push_container
