#!/usr/bin/env bash

cat <<EOT >> config/prod.secret.exs
use Mix.Config

config :hello, HelloWeb.Endpoint,
  secret_key_base: "$SECRET_KEY_BASE"

config :hello, Hello.Repo,
  url: "$DATABASE_URL",
  pool_size: 10,
  ssl: true
EOT
