#!/usr/bin/env bash

echo "______ Push Container to Heroku Registery _________ "

echo " here is where the work will happen"

# we push a release so that we have a hook to do any
# other deployment tasks before we send out the container
heroku container:push release --app=$HEROKU_APP

