#!/usr/bin/env bash

echo "______ Push Container to Heroku Registery _________ "


echo "------ generate prod.secret.exs file -------------"
./build_scripts/generate_secrets

heroku container:login
# we push a release so that we have a hook to do any
# other deployment tasks before we send out the container
heroku container:push web --app=$HEROKU_APP

